include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - unnecessary_const
    - unnecessary_new
    - avoid_function_literals_in_foreach_calls
    - prefer_collection_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - sort_child_properties_last
    - use_key_in_widget_constructors